# Generated by Django 5.2.4 on 2025-07-27 18:09

from django.db import migrations
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType

content_type_global, created = ContentType.objects.get_or_create(app_label='users_app', model='Global')
    

def add_permissions(apps, schema_editor):
 
    Permission.objects.get_or_create(
        codename='can_manage_users',
        name='Може керувати правами користувачів',
        content_type=content_type_global
    )

    Permission.objects.get_or_create(
        codename='can_watch_permissions',
        name='Може оглядати права користувачів',
        content_type=content_type_global
    )

    Permission.objects.get_or_create(
        codename='can_change_permissions',
        name='Може змінювати права користувачів',
        content_type=content_type_global
    )


def rollback_permissions(apps, schema_editor):
    Permission.objects.filter(
        content_type=content_type_global, 
        codename__in=[
            'can_manage_users', 
            'can_watch_permissions', 
            'can_change_permissions'
            ]).delete()



class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_appusers_phone'),
    ]

    operations = [
        migrations.RunPython(code=add_permissions, reverse_code=rollback_permissions),
    ]
