# Generated by Django 5.2.4 on 2025-07-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_report_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialreport',
            options={'ordering': ['-created_at'], 'permissions': [('can_watch_reports', 'User can watch the reports'), ('can_export_reports', 'User can export the reports')]},
        ),
    ]
