# Generated by Django 5.2.4 on 2025-07-24 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_report_app', '0002_alter_financialreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialreport',
            options={'ordering': ['-created_at'], 'permissions': [('can_watch_reports', 'User can watch the reports'), ('can_export_reports', 'User can export the reports')], 'verbose_name': 'Фінансовий звіт', 'verbose_name_plural': 'Фінансові звіти'},
        ),
    ]
