# Generated by Django 5.2.4 on 2025-08-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_report_app', '0004_alter_financialreport_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
                ('file_name', models.CharField(max_length=200, verbose_name='Назва файлу')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('word_count', models.IntegerField(default=0, verbose_name='Кількість слів у файлі')),
                ('char_count', models.IntegerField(default=0, verbose_name='Кількість символів у файлі')),
            ],
            options={
                'verbose_name': 'Завантажений файл',
                'verbose_name_plural': 'Завантажені файли',
            },
        ),
    ]
