# Generated by Django 5.2.5 on 2025-08-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_report_app', '0006_financialreport_total_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='financialreport',
            name='total_expenses',
        ),
        migrations.RemoveField(
            model_name='financialreport',
            name='total_income',
        ),
    ]
