# Generated by Django 5.2.4 on 2025-07-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_transaction', models.CharField(choices=[('income', 'Дохід'), ('expense', 'Витрата')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('transaction_date', models.DateField()),
                ('is_planned', models.BooleanField(default=False)),
                ('transaction_document', models.FileField(blank=True, null=True, upload_to='transaction_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['transaction_date', 'amount'],
            },
        ),
    ]
