# Generated by Django 5.2.5 on 2025-08-16 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='transactions_app.clients'),
        ),
    ]
